### ISSUE TITLE
Highlighting the next word

### ISSUE THREAD

**Issue by ishanray** [sjns19/typely#1]
It's a bit hard to figure out which word is the next one. Highlighting that would be nice. I quite like how this one does it: https://cybertype.app/

**Comment by sjns19** [comment]
Hi, thanks for the suggestion. I have updated it to highlight the upcoming word. However I decided not to do so for the single letter/number test as unpredicted next number/letter would make it a bit more challenging I guess.

And sorry for taking this long to look at your suggestion.
